name: Bot automerge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if:
      (github.event.pull_request.user.login == 'dependabot[bot]' ||
      github.event.pull_request.user.login == 'pre-commit-ci[bot]') &&
      github.repository == 'henryiii/check-sdist'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run:
          gh pr merge --auto --squash "${{github.event.pull_request.html_url}}"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
